mysql:
    host: localhost
    user: root
    passwd: my secret password
    db: write-math

elasticsearch:
    user: 
    passwd: 
    scheme: http
    host: es.pic.es
    port: 9200
    output_url: gsiftp://grid.magic.iac-test.pic.es:2811//data/
    
rucio_user:
    account: root 
    scope: test-orm

rucio_transfer:
    dstRSEs: PIC-DET-2 
    orgRSE: ORM-NON-DET-TEST 
    working_folder: Server-test 
    realistic_path: True 
    experiment: MAGIC 
    input_file: MAGIC_track.txt 
    prefix_output_file: MAGIC
